---
title: "Best Practices in R"
---


The goal of this training is to build better practices with programming in R, in order to enhance your productivity in research, and to minimize the time you spend on fixing, rewriting and debugging your R scripts.

To achieve this, you will learn how to start using R projects, and how to integrate version control with Github into your projects.

We'll look at syntax conventions and debugging tools, and we practice upgrading quick-and-dirty scripts to versatile R code.

To this end, we explain the theory and provide examples and hands-on to consolidate best pracices in R.

The idea is to learn how to create clean, readable, versatile and reproducible R workflows, which help boosting your scientific productivity and collaboration.

# Learning outcomes

When you complete this training you will

- know how to create and use R projects
- be able to store or publish your R project in GitHub
- be able to debug your code with R Studio tools
- know how to make your code reproducible and communicate it
- have an idea of style guidelines and their importance
- be able to make your code cleaner and more compact
- know the difference between some useful file formats
- know about literate programming

# Schedule

Total duration: 3 hours

TBD

# Training materials

<div>
```{=html}
<iframe class="slide-deck" src="../slides/index.html"></iframe>
```
</div>

# Prerequisites

You will need some experience with R, and a GitHub account.
You should also have R, R Studio and Git installed (or a vsc account and access to Open OnDemand).

# Trainers

- Mariana Montes ([mariana.montes@kuleuven.be](mailto:mariana.montes@kuleuven.be))
